read_depth: 8
allele_freq: 0.01

cohorts:
  - derivation_primary
  - derivation_metastatic
  - validation

cnv_cohorts:
  - primary
  - metastatic
  - sdh
  - wt

samples:
  - PP002-DZ3A
  - PP002-DZ4A
  - PP002-DZ5A
  - PP008-DZ2A
  - PP009-DZ1B
  - PP009-DZ2B
  - PP010-DZ1A
  - PP010-DZ5A
  - PP010-F2
  - PP019-DZ1A
  - PP053-DZ1B
  - PP053-DZ2C
  - PP053-DZ3A
  - PP086-DZ1A
  - PP100-DZ3A
  - PP103-DZ1A
  - PP103-DZ2A
  - PP104-DZ1A
  - PP104-DZ2A
  - PP106-DZ1A
  - PP113-DZ3B
  - PP117-DZ1A
  - PP117-DZ3A
  - PP119-DZ2A
  - PP119-DZ3A
  - PP125-DZ1A
  - PP126-DZ1A
  - PP126-DZ2A
  - PP136-DZ1A
  - PP176-DZ2A
  - PP176-DZ3B
  - PP192-DZ1A
  - PP192-DZ2A
  - PP220-DZ1A
  - PP220-DZ2A
  - PP220-DZ3A
  - PP245-DZ1A
  - PP245-DZ2A
  - PP253-DZ1A
  - PP253-DZ2A
  - PP263-DZ2A
  - PP302-DZ1A
  - PP323-DZ3A
  - PP323-DZ4A
  - PP323-DZ5A
  - PP341-DZ2B
  - PP344-DZ1A
  - PP344-DZ3A